name: Publish
permissions:
  contents: write
  id-token: write
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          version: latest
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run test
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
